- Nine Divisors.cpp
Added C++ program for the problem.
> Added Nine Divisors.cpp

- 235-lowest-common-ancestor-of-a-binary-search-tree/235-lowest-common-ancestor-of-a-binary-search-tree.py
28 / 28 test cases passed.
Runtime: 131 ms
Memory Usage: 18.7 MB
Submitted: 1 minute ago
Leetcode
> Create  235-lowest-common-ancestor-of-a-binary-search-tree.py

- Case-specific Sorting of Strings.py
Problem of the Day  : GFG 
Test Cases Passed: 
10063 /10063
Total Points Scored: 
4 /4
> Create Case-specific Sorting of Strings.py

- Case-specific Sorting string.cpp
gfg potd solution in cpp using indexing
> Create Case-specific Sorting string.cpp

- Max length chain
Problem of the day(13/08/2022) solved in c++
> Create Max length chain

- Two Sum.py
57 / 57 test cases passed.
Runtime: 60 ms
Memory Usage: 15.2 MB
Your runtime beats 97.37 % of python3 submissions.
Leetcode
> Create Two Sum.py

- 53-maximum-subarray/Maximum Subarray.py
209 / 209 test cases passed.
Runtime: 649 ms
Memory Usage: 27.9 MB
Your runtime beats 99.86 % of python3 submissions
> Create Maximum Subarray.py

- Merge Two Sorted Array.py
59 / 59 test cases passed.
Runtime: 58 ms
Memory Usage: 13.8 MB
Your runtime beats 51.40 % of python3 submissions.
> Create Merge Two Sorted Array.py

- 30-substring-with-concatenation-of-all-words/Create Substring with Concatenation.py
Daily Challenge for August Leetcoding Challenge 2022
178 / 178 test cases passed.
Runtime: 76 ms
Memory Usage: 14.4 MB
Your runtime beats 98.06 % of python3 submissions.
> Create Create Substring with Concatenation.py

- Friends Pairing Problem.cpp
> Added Friends Pairing Problem.cpp

- Friends Pairing Problem DP.java
Created a file for friends pairing problems with DP approach.
> Create Friends Pairing Problem DP.java

- Edit Distance.cpp
DP Solution of Edit Distance (Leetcode)
> Edit Distance Leetcode

- Number of Turns in Binary Tree.cpp
This is a C++ Solution to the problem "Number of Turns in Binary Tree"
Problem link: https://practice.geeksforgeeks.org/problems/number-of-turns-in-binary-tree/1
> Number of turns in binary tree C++ Solution.

- Fact Digit Sum.cpp
This is a C++ solution to the problem "Fact Digit Sum"
Problem link:  https://practice.geeksforgeeks.org/problems/fact-digit-sum4125/1
> Fact Digit Sum C++ Solution

- Number of Turns in Binary Tree.cpp
Using Space, O(height of Tree)
Time Complexity : O(N)
> New Approach for the Number of Turns in Binary Tree

- Knight Walk Problem.cpp
Added Another Memory Utilization Approach, BFS Algorithm, with Explanation.
> Another Approach

- 695-max-area-of-island/SolutionCode.cpp
Runtime: 15 ms, faster than 99.87% of C++ online submissions for Max Area of Island.
Memory Usage: 23.2 MB, less than 96.95% of C++ online submissions for Max Area of Island.
> Runtime: 15 ms (99.87%)  Memory Usage: 23.2 MB (96.95%)

- Word Ladder II.py
35 / 35 test cases passed.
Runtime: 57 ms
Memory Usage: 15 MB
Daily challenge for August Leetcoding challenge 2022
> Create Word Ladder II.py

- Longest Sub-Array with Sum K.cpp
This is the C++ Solution of the problem "Longest Sub-Array with Sum K"
Problem link: https://practice.geeksforgeeks.org/problems/longest-sub-array-with-sum-k0809/1
> C++ Solution of Longest Sub-Array with Sum K

- Unit Area of largest region of 1's.cpp
Both codes work equally but I am proposing more clean code than earlier.
> Another solution

- Unit Area of largest region of 1's.java
Tried to reduce no. of lines in the dfs function by simply using a loop to run over for 8 different directions.
> Update Unit Area of largest region of 1's.java

- 659-split-array-into-consecutive-subsequences/659-split-array-into-consecutive-subsequences.cpp
This the C++ Solution of the problem "Split Array into Consecutive Subsequences"
> Create Split Array into Consecutve Subsequences

- Sum of two large numbers.cpp
This is the C++ Solution to the problem "Sum of Two Large Numbers"
Problem link: https://practice.geeksforgeeks.org/problems/sum-of-numbers-or-number1219/1
> Created Sum of two large numbers

- 871. Minimum Number of Refueling Stops.cpp
A car travels from a starting position to a destination which is target miles east of the starting position.
There are gas stations along the way. The gas stations are represented as an array stations where stations[i] = [positioni, fueli] indicates that the ith gas station is positioni miles east of the starting position and has fueli liters of gas.
The car starts with an infinite tank of gas, which initially has startFuel liters of fuel in it. It uses one liter of gas per one mile that it drives. When the car reaches a gas station, it may stop and refuel, transferring all the gas from the station into the car.
Return the minimum number of refueling stops the car must make in order to reach its destination. If it cannot reach the destination, return -1.
Note that if the car reaches a gas …
> Create 871. Minimum Number of Refueling Stops.cpp

- Maximum Path Sum between 2 Leaf Nodes.cpp
> Create Maximum Path Sum between 2 Leaf Nodes.cpp

- 936-stamping-the-sequence/Stamping The Sequence.cpp
This is the solution to the problem "Stamping The Sequence"
> Created Stamping The Sequence CPP file

- Game with nos
The problem of the day of gfg. (21/08/2022)
> Create Game with nos.cpp

- Split_Array_Into_Consecutive_subsequence.java
Split Array into Consecutive Subsequences
(Medium: Leetcode 659)
You are given an integer array nums that is sorted in non-decreasing order.
Determine if it is possible to split nums into one or more subsequences such that both of the following conditions are true:
Each subsequence is a consecutive increasing sequence (i.e. each integer is exactly one more than the previous integer).
All subsequences have a length of 3 or more.
Return true if you can split nums according to the above conditions, or false otherwise.
A subsequence of an array is a new array that is formed from the original array by deleting some (can be none) of the elements without disturbing the relative positions of the remaining elements. (i.e., [1,3,5] is a subsequence of [1,2,3,4,5] while [1,3,2] is not).
> Leetcode Potd : 659

- Burning Tree.cpp
This is a C++ solution to the problem "Burning Tree"
Problem link: https://practice.geeksforgeeks.org/problems/burning-tree/1
> Created Burning Tree.cpp

- 16. 3Sum Closest - leetcode/SolutionCode.cpp
Runtime: 343 ms, faster than 96.04% of C++ online submissions for 3Sum Closest.
Memory Usage: 16.4 MB, less than 81.42% of C++ online submissions for 3Sum Closest.
> leetcode medium level coding problem

- 15. 3Sum/SolutionCode.cpp
Success Accepted Solution at Leetcode, 
Related Topic :  sorting, Hashing, Two Pointers, Array
> get all sum 3 elements of sum 0 from array

- Foldable Binary Tree.cpp
This is the C++ Solution to the problem "Foldable Binary Tree"
Problem link: https://practice.geeksforgeeks.org/problems/foldable-binary-tree/1
> Created Foldable Binary Tree.cpp

- 234. Palindrome Linked List/SolutionCode.cpp
Runtime: 257 ms, faster than 95.01% of C++ online submissions for Palindrome Linked List.
Memory Usage: 114 MB, less than 96.26% of C++ online submissions for Palindrome Linked List.
> Create SolutionCode.cpp for Palindrome Linked List

- Generate IP Addresses.py
Generate IP Addresses 24-Aug POTD optimal python solution
> Create Generate IP Addresses.py

- Counting Elements in Two Arrays.cpp
This is the C++ solution to the problem "Counting Elements in Two Arrays"
Problem link: https://practice.geeksforgeeks.org/problems/counting-elements-in-two-arrays/1
> Created Counting Elements in Two Arrays.cpp

- Count Palindromic  Subsequence.cpp
geekforgeeks potd,
26 aug 2022
Count Palindromic Subsequence
Recursion + memorization approach
> Create Count Palindromic  Subsequence.cpp

- Immediate Smaller Element.py
The python version for immediate smaller element problem
> Create Immediate Smaller Element.py

- 1329-sort-the-matrix-diagonally/SolutionCode.cpp
Runtime: 8 ms, faster than 94.99% of C++ online submissions for Sort the Matrix Diagonally.
Memory Usage: 9.3 MB, less than 72.67% of C++ online submissions for Sort the Matrix Diagonally.
> C++ Solution code of leetcode today's problem

- Merging Details _GFG.cpp
Here is the solution of Merging details GFG
> Create Merging Details _GFG.cpp

- Single Element in Sorted Array.py
> Create Single Element in Sorted Array.py

- Find pairs with given sum in doubly linked list.cpp
This is the C++ solution to the problem "Find pairs with given sum in doubly linked list"
Problem link: https://practice.geeksforgeeks.org/problems/find-pairs-with-given-sum-in-doubly-linked-list/1
> Create find pairs with given sum

- Find pairs with given sum in Doubly Linked List.java
Multiple Approaches with Complexities.
> Create Find pairs with given sum in Doubly Linked List.java

- Minimum Cost to cut a board into squares.cpp
This is the C++ solution to the problem "Minimum Cost to cut a board into squares"
Problem link: https://practice.geeksforgeeks.org/problems/minimum-cost-to-cut-a-board-into-squares/1
> Created Min cost to cut a board into squares.cpp

- MInimum time to fulfil all orders.cpp
This is the C++ solution to the problem " Minimum time to fulfill all orders"
Problem link: https://practice.geeksforgeeks.org/problems/minimum-time-to-fulfil-all-orders/1
> Created minimum time to fulfill all orders

- Merge Without Extra Space.cpp
Test Cases Passed:  317 /317
Your Total Score: 2954
Total Time Taken: 0.23
> Gfg Hard Category Question

- Allocate minimum number of pages.cpp
Time Complexity: O(NlogN)
Auxilliary Space: O(1)
> GFG Hard Tags : Divide and Conquer, Searching

- Reverse array in groups(GFG))
I have attached a solution to this question in java language.
_Given an array arr[] of positive integers of size N. Reverse every sub-array group of size K.
Note: If at any instance, there are no more subarrays of size greater than or equal to K, then reverse the last subarray (irrespective of its size)._
**Example 1:**
Input:
N = 5, K = 3
arr[] = {1,2,3,4,5}
Output: 3 2 1 5 4
Explanation: First group consists of elements
1, 2, 3. Second group consists of 4,5.
**Example 2:**
Input:
N = 4, K = 3
arr[] = {5,6,8,9}
Output: 8 6 5 9
_Your Task:
You don't need to read input or print anything. The task is to complete the function reverseInGroups() which takes the array, N and K as input parameters and modifies the array in-place._ 
**Expected Time Complexity: O(N)
Expected Auxiliary Space: …
> Reverse array in groups.java

- Print the pattern gfg sep_4.cpp
Like for n = 2 the pattern will be:
1*2*5*6
--3*4
n= shows the number of rows you need to make
> print the pattern sep 4 potd

- Print Pattern using String.java
Used 3 variables first, end and spaces.first-> to print first pattern numbers. spaces-> to print "-" symbols. end-> to print second pattern of symbols
> Create Print Pattern using String.java

- 876-middle-of-the-linked-list/876-middle-of-the-linked-list.java
- 876-middle-of-the-linked-list/README.md
876-Leetcode middle of the linkedlist(easy) Java solution
> Time: 0 ms (100.00%), Space: 42.3 MB (9.85%) - LeetHub

- Smallest sum contiguous subarray.cpp
This is the C++ solution to the problem "Smallest sum contiguous subarray"
Problem link: https://practice.geeksforgeeks.org/problems/smallest-sum-contiguous-subarray/1
> Created smallest sum contiguous subarray.cpp

- Book_Allcoation_Problem.cpp
> Create Book allocation Problem Answer File

- Smallest sum contiguous subarray.java
Used Sliding window Approach to calculate the minimum sum and Any time if sum>0, then we incremented i value and reduced the sum
> Update Smallest sum contiguous subarray.java

- Binary Tree Pruning.java
Binary Tree pruning is to delete a node if sub tree does not contains 1 as node
> Create Binary Tree Pruning.java

- Minimum sum of absolute difference of pairs.cpp
Problem of the day GFG
6 september 2022
Minimum sum of absolute difference of pairs 
Greedy approach
> Create Minimum sum of absolute difference of pairs.cpp

- Reverse array in groups(GFG))
Improving the time complexity and reverse logic
> Update Reverse array in groups(GFG))

- Sum of k smallest elements in BST.cpp
This is the C++ solution to the problem "Sum of k smallest elements in BST"
Problem link: https://practice.geeksforgeeks.org/problems/sum-of-k-smallest-elements-in-bst3029/1
> Created sum of k smallest elements in BST

- sum of k small element.cpp
Problem of the day GFG 
8 septempber 2022
Sum of k small element
> Create sum of k small element.cpp

- Kth smallest element.cpp
Kth smallest element in array in CPP geeks for geeks
> Create Kth smallest element.cpp

- 94. Binary Tree Inorder Traversal.cpp
leetcode daily Challenge sep 8 
TC:4ms MC:8.4MB
I am solve this problem using cpp
> Create 94. Binary Tree Inorder Traversal.cpp

- Largest prime factor.cpp
Expected Time Complexity: O(sqrt(N))
Expected Space Complexity: O(1)
> Create Largest prime factor.cpp

- sum of k smallest elements in  BST.cpp
Time complexity : O(N)
Space Complexity : O(N)
> Create sum of k smallest elements in  BST.cpp

- 237-delete-node-in-a-linked-list/237-delete-node-in-a-linked-list.java
237-delete-node-in-a-linked-list (Leetcode-medium)
> Time: 0 ms (100.00%), Space: 44.7 MB (6.33%) - LeetHub

- Smallest number with sum of digits as N and divisible by 10^N.cpp
This is the C++ solution to the problem "Smallest number with sum of digits as N and divisible by 10^N"
Problem link: https://practice.geeksforgeeks.org/problems/smallest-number-with-sum-of-digits-as-n-and-divisible-by-10n4032/1
> Created smallest number with sum  of digits as N

- Find-Pattern/find_patter.java
- Find-Pattern/question.md
Contributed a new question for your largest dsa repository, I hope it will be helpfull for the folks.
> :fire: find-pattern solution by Jatin

- Ball coloring.py
If you found my solution  useful then star  my repos and keep in touch for more solution like this.
> Create Ball coloring.py

- Longest Bitonic subsequence.cpp
Expected Time Complexity: O(n2)
Expected Space Complexity: O(n)
> Create Longest Bitonic subsequence.cpp

- Ball-Coloring/ball_coloring.java
- Ball-Coloring/question.md
Created the solution for the POTD gfg.
> :fire: solution for potd Ball-Coloring by jatin

- Best Time to Buy and Sell Stock IV.java
> Create Best Time to Buy and Sell Stock IV.java

- Ball coloring.java
class Solution {
static long noOfWays(long n){
// code here
return 2 + n * (n - 1);
}
}
> Create Ball coloring.java

- Count_occurences_of_a_given_word_in_a_2-d_array/Solution.java
- Count_occurences_of_a_given_word_in_a_2-d_array/question.md
Best Time complexity solution for the POTD.
> :fire: count-occurence-of-a-given-word-in-2d-array solution (POTD)

- Count occurrences of a given word in a 2-d array.py
> Create Count occurrences of a given word in a 2-d array.py

- Ball Coloring.cpp
https://practice.geeksforgeeks.org/problems/ball-coloring3450/1
> Ball Coloring.cpp

- Bag Of Tokens.java
> Create Bag Of Tokens.java

- Minimum Exchange GFG/MinimumExchange.cpp
> updated Minimum exchange.cpp

- Power-of-2-&-Subsequences/Solution.cpp
- Power-of-2-&-Subsequences/question.md
POTD using c++ language there is some bug in the gfg compiler for the java solution.
> :fire: Power of 2 and Subsequences solution by Jatin

- Power of 2 and Subsequences.cpp
This is the C++ Solution to the problem "Power of 2 and Subsequences"
Problem link: https://practice.geeksforgeeks.org/problems/power-of-2-and-subsequences0759/1
> Created Power of 2 and subsequences.cpp

- Power Of 2 and Subsequences.cpp
c++ solution of gfg potd with comments
> gfg potd solution

- Smallest Subset with Greater Sum.Cpp
int minSubset(vector<int> &Arr,int N){
sort(Arr.begin(),Arr.end());
long long int sum=0;
for(int i=0;i<N;i++)
sum+=Arr[i];
long long int x=0;
int count=1;
for(int j=N-1;j>=1;j--)
{
x+=Arr[j];
if(x>sum-x)
break;
count++;
}
return count;
}
> Create Smallest Subset with Greater Sum.Cpp

- Find Original Array From Doubled Array.java
> Create  Find Original Array From Doubled Array.java

- Number-of-ways-to-arrive-destination/Solution.cpp
- Number-of-ways-to-arrive-destination/question.md
Easy to understand and efficient time complexity code.
> :fire: number of ways to reach the destination by Jatin

- Partition Labels .cpp
Leetcode Medium
You are given a string s. We want to partition the string into as many parts as possible so that each letter appears in at most one part.
Note that the partition is done so that after concatenating all the parts in order, the resultant string should be s.
Return a list of integers representing the size of these parts.
> Create Partition Labels .cpp

- Composite And Prime.java
Geeks For Geeks Problem Of Day
> Composite And Prime.java

- Composite and Prime.py
Approach using sieve of Eratosthenes in Python 3.9.
> Create Composite and Prime.py

- Reverse-Interger.java
A condition that check each and every test case of being reverse.
> Java solution for 7. Reverse Integer

- 143-Reorder List.java
> Create 143-Reorder List.java

- License Key Formatting.cpp
> Create License Key Formatting.cpp

- License Key Formatting.java
> Create License Key Formatting.java

- Reverse a Stack using Recursion.cpp
Geeks For Geeks problem's solution ..reversal of stack using recursion
> Create Reverse a Stack using Recursion.cpp

- Licence Key Formatting.java
Simple To Understand And Easy To Implement.
> Licence Key Formatting.java

- IPL 2021 - Match Day 2.cpp
This is the C++ solution to the Solution "IPL 2021 - Match Day 2"
Problem link : https://practice.geeksforgeeks.org/problems/deee0e8cf9910e7219f663c18d6d640ea0b87f87/1
> Create IPL 2021-Match Day 2.cpp

- IPL 2021 - Match Day 2 by AMAN SAINI
THIS CODE WILL USE priority_queue<pair<int, int>> THAT CAN HELP PEOPLE TO CLEAR MORE THEIR CONCEPTS.
> Create IPL 2021 - Match Day 2 by AMAN SAINI

- Geek and Number String.cpp
This is the C++ Solution to the problem "Geek and Number String"
Problem link: https://practice.geeksforgeeks.org/problems/904237fa926d79126d42c437802b04287ea9d1c8/1
> Create Geek and Number String.cpp

- Geek and Number String.java
Geeks For Geeks Problem Of Day For 23-09-2022
> Create Geek and Number String.java

- Path Sum ||.java
LeetCode Question Of Day For 24-September-2022
> Path Sum ||.java

- The bit Game.cpp
I have done the code of The Bit Game problem in cpp
> Create The bit Game.cpp

- Average of level in Binary tree.cpp
I have solved The problem Of Create Average of level in Binary tree Of Leetcode. In the solution I had tried to explain the code
> Create Average of level in Binary tree.cpp

- GFG/Fitting The Array/Fitting The Array.cpp
This is the C++ Solution to the problem "Fitting The Array"
Problem link: https://practice.geeksforgeeks.org/problems/fitting-the-array1514/1
> create fitting the array

- Leetcode/19 Remove Nth Node From End of List/Remove Nth Node from End Of List.java
> Remove Nth Node from End Of List.java

- GFG/Sort an array of 0s, 1s and 2s/Sort an array of 0s,1s and 2s s29.cpp
- [❌ ] Added problem statement(Readme.md) with solution?
- [ ✅] Contributing new file?
- [ ✅] GFG 
- [ ✅] Added file with correct name and correct directory?
>  sort an array 0s, 1s and 2s s29

- Leetcode/658 Find K Closest Elements/658 Find K Closest Elements s29.cpp
- [❌ ] Added problem statement(Readme.md) with solution?
- [ ✅] Contributing new file?
- [ ✅] Leetcode 
- [✅ ] Added file with correct name and correct directory?
>  Find K closest elements lc

- Leetcode/658 Find K Closest Elements/Find k Closest Elements.java
> Find k Closest Elements.java

- GFG/Find The Safe Position/Find The Safe Position s30.cpp
- Leetcode/218 The Skyline Problem/218 The Skyline Problem s30.cpp
- [ ✅] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?
- [ ❌] Added problem statement(Readme.md) with solution?
- [✅ ] Contributing new file?
- [✅] Leetcode 
- [✅ ] GFG 
- [ ✅] Added file with correct name and correct directory?
>  Find the safe position

- GFG/Find The Safe Position/Find the Safe Position.java
Geeks For Geeks Problem Of Day for 30-09-2022
> Create Find the Safe Position.java

- GFG/Number of Distinct Islands/Number of Distinct Islands oct1.cpp
- Leetcode/91 Decode Ways/91 Decode Ways oc1.cpp
- [ ✅] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?
- [❌] Added problem statement(Readme.md) with solution?
- [ ✅] Contributing new file?
- [✅ ] Leetcode 
- [✅ ] GFG 
- [✅ ] Added file with correct name and correct directory?
> Number of Distinct Islands gfg + decode ways lc

- Leetcode/1155. Number of Dice Rolls With Target Sum/1155. Number of Dice Rolls With Target Sum.py
> Create 1155. Number of Dice Rolls With Target Sum.py

- Leetcode/Remove Letter To Equalize Frequency/Remove Letter To Equalize Frequency.cpp
> Create Remove Letter To Equalize Frequency.cpp

- GFG/Minimum characters to be added at front to make string palindrome/Minimum characters to be added at front to make string palindrome.java
> Minimum characters to be added at front to make string palindrome.java

- GFG/Minimum characters to be added at front to make string palindrome/Minimum characters to be added at front to make string palindrome.cpp
- GFG/Minimum characters to be added at front to make string palindrome/README.md
https://practice.geeksforgeeks.org/problems/minimum-characters-to-be-added-at-front-to-make-string-palindrome/1
> GFG problem of the day 

- GFG/Replace O's with X's/Replace O's with X's.cpp
[Link to the problem]()  
(https://practice.geeksforgeeks.org/problems/replace-os-with-xs0052/1)
> Create Replace O's with X's.cpp

- Leetcode/4. Median of Two Sorted Arrays/4. Median of Two Sorted Arrays.java
> Create 4. Median of Two Sorted Arrays.java

- GFG/Number of Distinct Islands/Number of Distinct Islands oct1.cpp
> Update Number of Distinct Islands oct1.cpp

- 2429-minimize-xor/2429-minimize-xor.cpp
- 2429-minimize-xor/Readme.md
- [✅ ] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?
- [ ✅ ] Added problem statement(Readme.md) with solution?
- [ ✅ ] Contributing new file?
- [✅  ] Leetcode
> Add 2429-minimiza-xor solution. (LeetCode)

- Leetcode/104-maximum-depth-of-binary-tree/104-maximum-depth-of-binary-tree.cpp
- Leetcode/104-maximum-depth-of-binary-tree/README.md
>  104-maximum-depth-of-binary-tree

- Leetcode/2424. Longest Uploaded Prefix/2424. Longest Uploaded Prefix.java
> LEETCODE QUESTION 2424. Longest Uploaded Prefix ADDED

- Leetcode/Number of Dice rolls with target sum/Number of dice rolls.cpp
I have solved the leetcode 1155 Number of dice rolls with a given sum using Dynamic Programming
> Number of dice rolls solved with DP

- GFG/Search Pattern (Rabin-Karp Algorithm)/Search Pattern (Rabin-Karp Algorithm).java
> Create Search Pattern (Rabin-Karp Algorithm).java

- GFG/Modified Numbers and Queries/Modified Numbers and Queries.py
> Create Modified Numbers and Queries.py

- GFG/Modified Numbers and Queries/Modified Numbers and Queries.cpp
- GFG/Modified Numbers and Queries/README.md
> Modified Numbers and Queries GFG POTD

- GFG/Spiral Matrix/Spiral Matrix.cpp
> Create Spiral Matrix.cpp

- Leetcode/112 Path Sum/Path Sum.java
> Path Sum.java

- GFG/Count all possible paths from top left to bottom right/Count all possible paths from top left to bottom right.cpp
- GFG/Count all possible paths from top left to bottom right/README.md
> Count all possible paths from top left to bottom right - GFG POTD 

- 23-Merge-k-Sorted-Lists/23-Merge-k-Sorted-Lists.cpp
- 23-Merge-k-Sorted-Lists/README.md
> C++ Solution for Merge K Sorted List

- GFG/Modified Numbers and Queries/Modified Numbers And Queries.java
Used Sieve Algorithm to find answer
> Create Modified Numbers And Queries.java

- Leetcode/Minimum time to Make Rope Colorful/Minimum Time to Make Rope Colorful.cpp
- Leetcode/Sort Colors/Sort Colors.cpp
> Minimum Time to Make Rope Colorful solved using Greedy

- Leetcode/1578. Minimum Time to Make Rope Colorful/1578. Minimum Time to Make Rope Colorful.py
> 1578. Minimum Time to Make Rope Colorful.py

- GFG/Search Pattern (KMP-Algorithm)/Search Pattern (KMP-Algorithm).java
> Create Search Pattern (KMP-Algorithm).java

- Leetcode/2428. Maximum Sum of an Hour Glass/2428. Maximum Sum of an Hour Glass.cpp
> Create 2428. Maximum Sum of an Hour Glass in LeetCode

- GFG/Find the N-th character/Find the N-th character.cpp
> Create Find the N-th character.cpp

- Leetcode/237. Delete Node in a Linked List/Delete Node in a Linked List.cpp
> Create Delete Node in a Linked List.cpp

- GFG/Geek and Strings/Geek and Strings.java
- GFG/Geek and Strings/ReadMe.md
Mentioned in comments
- [x ] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?
- [x ] Contributing new file?
- [x ] GFG
> Create Geek and Strings.java

- Leetcode/623 Add One Row To Tree/Add one row to tree.java
- Leetcode/623 Add One Row To Tree/ReadMe.md
> Create Add one row to tree.java

- Leetcode/K diff pairs/K diff pairs.cpp
> Solved k diff pairs using Maps

- GFG/Kth smallest element/Kth smallest element.py
> Create Kth smallest element.py

- Leetcode/623 Add One Row to Tree/623 Add One Row to Tree.java
> Create 623 Add One Row to Tree.java (Today's leetcode daily challenge problem)

- Leetcode/2368. Reachable Nodes With Restrictions/Reachable Nodes With Restrictions.cpp
> Create Reachable Nodes With Restrictions.cpp

- Leetcode/1996. The Number of Weak Characters in the Game/The Number of Weak Characters in the Game.cpp
> Create The Number of Weak Characters in the Game.cpp

- Leetcode/92 Reverse Linked List II/Reverse Linked List II.cpp
> Create Reverse Linked List II.cpp

- Leetcode/4. Median of Two Sorted Arrays/Median of Two Sorted Arrays.cpp
> Create Median of Two Sorted Arrays.cpp

- Leetcode/19 Remove Nth Node From End of List/19 Remove Nth Node From End of List.cpp
> Update 19 Remove Nth Node From End of List.cpp

- Leetcode/75.Sort colors/Sort colors.cpp
> Create Sort colors.cpp

- Leetcode/1578 Minimum Time to Make Rope Colorful/1578 Minimum Time to Make Rope Colorful.cpp
> Update 1578 Minimum Time to Make Rope Colorful.cpp

- GFG/Merge two BST 's/Merge two BST.cpp
> Create Merge two BST.cpp

- GFG/Majority Element/Majority Element.java
- GFG/Majority Element/Majority Element.py
- GFG/Majority Element/README.md
> GFG | Medium | Majority element python solution

- GFG/Substrings of length k with k-1 distinct elements/Substrings of length k with k-1 distinct elements.cpp
> Create Substrings of length k with k-1 distinct elements.cpp

- Leetcode/Two Sum IV-Input is BST/Two Sum IV-Input is a BST.java
> Create Two Sum IV-Input is a BST.java

- GFG/Help Ishaan/Help Ishaan.java
> Create Help Ishaan.java

- GFG/Help Ishaan/Help Ishaan.java
> Added a different code for the solution at the end of the code.

- Leetcode/Break A Palindrome/Break A Palindrome.java
> Break A Palindrome.java

- Leetcode/104-maximum-depth-of-binary-tree/104. Maximum Depth of Binary Tree.java
> Create 104. Maximum Depth of Binary Tree.java

- GFG/Save Your Life/Save Your Life.cpp
This is the C++ Solution to the problem "Save Your Life"
Problem link : https://practice.geeksforgeeks.org/problems/save-your-life4601/1
> create save your life.cpp

- Leetcode/237. Delete Node in a Linked List/Delete Node in a Linked List.java
> Delete Node in a Linked List.java

- GFG/Save Your Life/Save Your Life.java
Another Approach to solve problem
> Update Save Your Life.java

- GFG/Maximize the sum of selected numbers from an array to make it empty/Maximize the sum of selected numbers from a sorted array to make it empty.cpp
- GFG/Maximize the sum of selected numbers from an array to make it empty/README.md
- [] Appending your code in already existing file?
> Added cpp and readme for Maximize the sum of selected numbers from a sorted array to make it empty

- GFG/Shortest Distance in a Binary Maze/Shortest Distance in a Binary Maze.java
> Update Shortest Distance in a Binary Maze.java

- Leetcode/1531. String Compression II/1531. String Compression II.cpp
> String compression ii.cpp

- GFG/Print Diagonally/Print Diagonally.cpp
- GFG/Replace every element with the least greater element on its right/README.md
- GFG/Replace every element with the least greater element on its right/Replace every element with the least greater element on its right.cpp
> Added cpp and Readme file for Replace every element with the least greater element on its right gfg

- Leetcode/151.Reverse Words in a String/Reverse Words in a String.java
> Reverse Words in a String.java

- 37-Sudoku-solver/37-Sudoku-solver.js
- 37-Sudoku-solver/README.md
-[x] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?
> sudoku solver Leetcode

- Leetcode/Top K Frequent Words/Top K Frequent Words.cpp
> Create Top K Frequent Words.cpp

- Leetcode/1662. Check If Two String Arrays are Equivalent/Check If Two String Arrays are Equivalent.java
> Check If Two String Arrays are Equivalent.java

- GFG/Chicks in a Zoo/Chicks in a Zoo.cpp
> Create chicks in a zoo.cpp

- Leetcode/766.Toeplitz Matrix/Toeplitz Matrix.java
> Toeplitz Matrix.java

- GFG/Phone directory/Phone directory.cpp
> Created Phone directory.cpp soluton

- GFG/Array Removals/Array Removals.cpp
> Create Array Removals.cpp

- GFG/Phone directory/Phone directory.java
Using Character Array And Boolean Array In trie and made some comments
> Update Phone directory.java

- GFG/Grouping Of Numbers/Grouping Of Numbers.java
> Update Grouping Of Numbers.java

- GFG/Minimum number of Coins/Minimum number of Coins.cpp
> Create Minimum number of Coins.cpp

- GFG/Minimum sum partition/Minimum sum partition.cpp
> Create Minimum sum partition.cpp

- GFG/Check for BST/Check for BST.java
> Create Check for BST.java

- Leetcode/2124. Check if All A's Appears Before All B's/2124. Check if All A's Appears Before All B's.java
> 2124. Check if All A's Appears Before All B's.java

- GFG/Jumping Numbers/Jumping Numbers.cpp
- GFG/Jumping Numbers/README.md
- GFG/Primes sum/Primes sum.cpp
- GFG/Primes sum/README.md
> Primes sum cpp solution

- GFG/Fill up buckets/Fill up buckets.cpp
- GFG/Maximum Sub-String after at most K changes/Maximum Sub-String after at most K changes.cpp
- GFG/Maximum Sub-String after at most K changes/README.md
> Create Maximum Sub-String after at most K changes.cpp and Fill up buckets.cpp

- GFG/Fill up buckets/Fill up buckets.cpp
> Update Fill up buckets.cpp

- Leetcode/222. Count Complete Tree Nodes/Count Complete Tree Nodes.java
> Create Count Complete Tree Nodes.java

- GFG/Alternate Vowel and Consonant String/Alternate Vowel and Consonant String.java
> Create Alternate Vowel and Consonant String.java

- GFG/Alex Travelling/Alex Travelling.cpp
- [ x] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?
- [ x] Contributing new file?
- [x ] GFG
> Create Alex Travelling.cpp

- GFG/Wine Buying and Selling/Wine Buying and Selling.java
Storing Positive in one Array and negative values in other and then calculated ans
> Update Wine Buying and Selling.java

- GFG/Container With Most Water/Container With Most Water.cpp
- [ x] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?
- [x ] Contributing new file?
- [x ] GFG
> Create Container With Most Water.cpp

- GFG/Largest subtree sum in a tree/Largest subtree sum in a tree.cpp
> Create Largest subtree sum in a tree.cpp

- GFG/Find minimum number of Laptops required/Find minimum number of Laptops required.cpp
- [ x] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?
- [x ] Contributing new file?
- [ x] GFG
> Create Find minimum number of Laptops required.cpp

- GFG/Count the Substring/Count the Substring.cpp
Count the substring
GFG problem
C++ solution
Clear all testcase
> Create Count the Substring.cpp

- 0012-integer-to-roman/0012-integer-to-roman.py
- 0026-remove-duplicates-from-sorted-array/0026-remove-duplicates-from-sorted-array.py
- 0036-valid-sudoku/0036-valid-sudoku.py
- 0038-count-and-say/0038-count-and-say.py
- 0049-group-anagrams/0049-group-anagrams.py
> Adding Python Solution

- 0079-word-search/0079-word-search.java
> Updated 0079-word-search.java

- 151. Reverse Words in a String.java
[151 ] Leetcode 
Added the Java code of [151. Reverse Words in a String](https://leetcode.com/problems/reverse-words-in-a-string/)]
Kindly merge the code.
Thank you
Tushar Paul
> Create 151. Reverse Words in a String.java

- Breadth first search.cpp
- depth first search.cpp
added graph traversal dfs and bfs
> added graph traversal bfs & dfs

- 0242-valid-anagram/0242-valid-anagram.cpp
> Added C++ solution to  0242-valid-anagram

- 0055-jump-game/0055-jump-game.py
- 0057-insert-interval/0057-insert-interval.py
> Adding Python Solution of Problems

- 1742. Maximum Number of Balls in a Box(leetcode)
>  1742. Maximum Number of Balls in a Box(leetcode)
